[package]
authors = ['GalacticCouncil']
edition = '2018'
homepage = 'https://github.com/galacticcouncil/hydradx-math'
license = 'Apache-2.0'
name = "hydra-dx-math"
description = "A collection of utilities to make performing liquidity pool calculations more convenient."
repository = 'https://github.com/galacticcouncil/hydradx-math'
version = "3.1.0"

[dependencies]
primitive-types = {default-features = false, version = '0.8.0'}
num-traits = {default-features = false, version = "0.2.14"}
fixed = "1.9.0"

[features]
default = ["std"]
std = []
