[package]
name = "hydra-dx-math"
version = "2.0.0"
authors = ['GalacticCouncil']
edition = "2018"

[dependencies]
lazy_static = {features = ['spin_no_std'], version = '1.4.0'}
primitive-types = {default-features = false, version = '0.7.2'}
num-traits = {default-features = false, version = "0.2.14"}

[features]
default = ["std"]
std = []
