name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: codota/toolchain@00a8bf2bdcfe93aefd70422d3dec07337959d3a4
        with:
          profile: minimal
      - name: Install clippy
        run: rustup component add clippy
      - name: Run clippy
        run: make clippy
        continue-on-error: false
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Test && Generate code coverage
        run: cargo tarpaulin --all-features --workspace --locked  --ignore-tests -o Xml -o lcov
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
      - name: Build release
        run: time cargo build --release --locked --quiet
