name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2021-05-01
          target: wasm32-unknown-unknown
          override: true
          default: true
      - name: Install clippy
        run: rustup component add clippy
      - name: Run clippy
        run: cargo clippy --release -- -D warnings
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Test && Generate code coverage
        run: cargo tarpaulin --all-features --workspace --locked  --ignore-tests -o Xml -o lcov
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          # token:                ${{secrets.CODECOV_TOKEN}} # not required for public repos
          fail_ci_if_error: true
      - name: Build release
        run: time cargo build --release --locked --quiet
